### ISSUE TITLE
This command : /?, generate an error.

### ISSUE THREAD

**Issue by fabien91** [Pwn9/PwnFilter#12] opened 2015-06-14 19:14 UTC
My error when i write /? in minecraft chat : http://pastebin.com/rFe9Ntu9

**Comment by DreamPhreak** [comment] 2015-06-14 20:42
Have you tried \? instead of /?

**Comment by ptoal** [comment] 2015-09-13 14:29
Sorry for taking so long to get back to this.  Did you resolve the problem?  This looks like an error in one of your conditions in your rules file.  Eg:
```
match blah
ignore string ?
then whatever
```
This isn't a bug in PwnFilter, per se, though it would be nice if we had a more friendly handling for unescaped regex in matches like this.

If you're still tracking this, please let me know, otherwise, I will close it in a week or so.

**Comment by ptoal** [comment] 2015-09-13 20:00
I see... The problem is actually in one of our sample files:
```
match ^/\?
rule A4
require command ?
then deny
```
I have fixed it by escaping the ? in the "require command" line.

**Closed by ptoal** 2015-09-13 20:00 UTC
